on: [push, pull_request]

jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-22.04
    name: Build on ubuntu-22.04 armv7
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu22.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
            sudo apt-get update
            sudo apt-get install -y \
            build-essential \
            libgl1-mesa-dev \
            libx11-dev \
            libxcb1-dev \
            libx11-xcb-dev \
            libxext-dev \
            libxfixes-dev \
            libxi-dev \
            libxrender-dev \
            libxcb-glx0-dev \
            libxcb-keysyms1-dev \
            libxcb-image0-dev \
            libxcb-shm0-dev \
            libxcb-icccm4-dev \
            libxcb-sync0-dev \
            libxcb-xfixes0-dev \
            libxcb-shape0-dev \
            libxcb-randr0-dev \
            libxcb-render-util0-dev \
            libxcb-util0-dev \
            libxcb-xinerama0-dev \
            libxcb-xkb-dev \
            xkb-data \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            wget
            wget https://download.qt.io/archive/qt/6.5/6.5.3/single/qt-everywhere-src-6.5.3.tar.xz
            tar -xf qt-everywhere-src-6.5.3.tar.xz
            rm qt-everywhere-src-6.5.3.tar.xz
            cd qt-everywhere-src-6.5.3
            ./configure -release -opensource -confirm-license -nomake examples -nomake tests
            make -j$(nproc)
            
      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
